"""Initial schema: enums, all tables, partitioning, materialized views.

This migration is intentionally hand-authored (rather than autogenerated) because
it must create PostgreSQL features SQLAlchemy's autogenerate doesn't model:
native enum types created up-front (so create order is irrelevant), RANGE
partitioning for the fact tables, the partition-management function, and the
dashboard materialized views.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-17
"""

from __future__ import annotations

from alembic import op

from app.db import ddl
from app.db.base import Base

# Register all tables on Base.metadata.
import app.models  # noqa: F401,E402

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    # gen_random_uuid() (pgcrypto provides it on older PG; core on PG13+).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # 1) Native enum types first → table create order becomes irrelevant.
    for stmt in ddl.create_enum_sql():
        op.execute(stmt)

    # 2) All tables + indexes from the ORM metadata (types already exist).
    Base.metadata.create_all(bind=bind, checkfirst=True)

    # 3) Partition management function + default/rolling monthly partitions.
    op.execute(ddl.PARTITION_FUNCTION_SQL)
    for stmt in ddl.default_partitions_sql():
        op.execute(stmt)
    for stmt in ddl.rolling_partitions_sql():
        op.execute(stmt)

    # 4) Dashboard materialized views (executed statement-by-statement).
    for stmt in (s.strip() for s in ddl.MATVIEWS_SQL.split(";")):
        if stmt:
            op.execute(stmt)


def downgrade() -> None:
    bind = op.get_bind()
    for name in reversed(ddl.MATVIEW_NAMES):
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS {name} CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS ls_create_month_partition(text, timestamptz);")
    Base.metadata.drop_all(bind=bind)
    for _, name in reversed(ddl.ENUM_TYPES):
        op.execute(f"DROP TYPE IF EXISTS {name} CASCADE;")
